---
# Common connection options
ansible_python_interpreter : /usr/bin/python3
ansible_user               : vyos
# ansible_ssh_private_key    : ~/.ssh/id_rsa
ansible_ssh_pass           : vyos_pass
ansible_network_os         : vyos
ansible_connection         : ansible.netcommon.network_cli
gather_facts               : false

